// Library includes
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <memory>
#include <vector>

// STM32 includes
#include "dac.h"
#include "dma.h"
#include "stm32f767xx.h"
#include "stm32f7xx_hal.h"
#include "stm32f7xx_hal_dac.h"
#include "stm32f7xx_hal_tim.h"
#include <gpio.h>
#include <main.h>
#include <tim.h>
#include <usart.h>

// Custom includes
#include <quantized_looper/hardware/led.hpp>
#include <quantized_looper/software/led_tasks.hpp>
#include <quantized_looper/utils/logger_singleton.hpp>
#include <reusable_synth/hardware/pin_change.hpp>
#include <reusable_synth/middleware/debounced_button.hpp>
#include <reusable_synth/software/task.hpp>
#include <reusable_synth/software/wavetable_osc.hpp>

// Helper functions generated by CubeMX
extern "C"
{
    extern void SystemClock_Config();
}

auto logger = LoggerSingleton::get();

// Tap tempo globals
static constexpr uint32_t MIN_CYCLE_TIME = 250;  // Max of 240 BPM
static constexpr uint32_t MAX_CYCLE_TIME = 3000; // Min 20 BPM

// TODO: move task
// TODO: writer interface not tied to UART
extern UART_HandleTypeDef huart3;
void task_print_logs()
{
    auto log = logger->remove_log();
    if (log.has_value()) {
        const char* msg = log->pBuffer();
        // TODO: flush log in non-blocking mode using HAL_UART_Transmit_IT or
        (void)msg;
        // HAL_UART_Transmit_DMA HAL_UART_Transmit(&huart3, (uint8_t*)msg,
        // strlen(msg), 100); HAL_UART_Transmit(&huart3, (uint8_t*)"\r\n", 2,
        // 100);
    }
}

// TODO: move button code to its own file
// TODO: Creation of this can be automated with cubemx
extern "C" void EXTI15_10_IRQHandler(void)
{
    HAL_GPIO_EXTI_IRQHandler(USER_Btn_Pin);
}

static std::array<PinChange::RegisteredPin, 1> registeredPins;
static std::chrono::duration<uint32_t, std::milli> debounceTime(MIN_CYCLE_TIME);
static DebouncedButtonEdge<std::chrono::duration<uint32_t, std::milli>>
  tempoButton(
    registeredPins,
    USER_Btn_Pin,
    []() -> std::chrono::duration<uint32_t, std::milli> {
        return std::chrono::duration<uint32_t, std::milli>(HAL_GetTick());
    },
    debounceTime);

// TODO: move button timing to its own file
template<typename TickType>
class ButtonTime
{
public:
    ButtonTime(TickType (*getTime)())
      : getTime(getTime)
    {
    }

    void irq()
    {
        TickType time = getTime();
        last_diff = time - last_time;
        last_time = time;
    }
    TickType getDiff() { return last_diff; }

private:
    TickType (*getTime)();
    volatile TickType last_time;
    volatile TickType last_diff;
};

extern "C" void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    PinChange::irq_dispatch(registeredPins, GPIO_Pin);
}

// TODO: write DAC driver and move this in there
extern TIM_HandleTypeDef htim2;
extern DAC_HandleTypeDef hdac;
static constexpr int dacDmaBufSize = 256;
static constexpr int dacDmaBufHalfSize = dacDmaBufSize / 2;
static uint32_t outputBuffer[dacDmaBufSize] = { 0 };
volatile static bool writeFront = true;
extern "C" void HAL_DAC_ConvHalfCpltCallbackCh1(DAC_HandleTypeDef* hdac)
{
    writeFront = true;
}
extern "C" void HAL_DAC_ConvCpltCallbackCh1(DAC_HandleTypeDef* hdac)
{
    writeFront = false;
}

int main()
{
    HAL_Init();

    SystemClock_Config();

    MX_GPIO_Init();
    HAL_NVIC_SetPriority(EXTI15_10_IRQn, 5, 0); // Lower priority than system
    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
    MX_DMA_Init();
    MX_DAC_Init();
    MX_TIM2_Init();
    MX_TIM3_Init();
    MX_USART3_UART_Init();

    // Button press TODO move to its own file
    ButtonTime buttonTime(HAL_GetTick);
    tempoButton.registerEdgeCallback([&buttonTime]() { buttonTime.irq(); });

    // DAC waveform
    auto status = HAL_TIM_Base_Start(&htim2);
    assert_param(status == HAL_OK);
    status = HAL_DAC_Start_DMA(
      &hdac, DAC_CHANNEL_1, outputBuffer, dacDmaBufSize, DAC_ALIGN_12B_R);

    assert_param(status == HAL_OK);
    // Task to keep DAC on track
    auto lastWriteFront = false;
    auto rampTable = RampWavetable<uint32_t, 1024, 0, (1 << 12) - 1>();
    WavetableOsc<uint32_t> osc(rampTable.data);
    osc.setFrequency(100, 96000);
    auto writeRamp = [&lastWriteFront, &osc]() {
        if (lastWriteFront != writeFront) {
            lastWriteFront = writeFront;
            auto ptr =
              writeFront ? outputBuffer : outputBuffer + dacDmaBufHalfSize;
            osc.increment(std::span(ptr, dacDmaBufHalfSize));
        }
    };

    // Create LED handlers
    auto led1 = Led<TIM_HandleTypeDef>(
      &htim3, TIM_CHANNEL_3, MX_TIM3_Init, MX_TIM3_DeInit);
    auto led2 = Led<GPIO_TypeDef>(LD2_GPIO_Port, LD2_Pin);
    auto led3 = Led<GPIO_TypeDef>(LD3_GPIO_Port, LD3_Pin);

    // Create LED tasks
    using millis = std::chrono::duration<uint32_t, std::milli>;
    auto led1Breathe = LedBreatheAnimation(&led1, millis(1000));
    auto led2Toggle = LedToggleAnimation(&led2);
    auto led3Toggle = LedToggleAnimation(&led3);

    // Organize tasks in priority list
    std::array<std::unique_ptr<TaskControlBlockInterface<millis>>, 6> tasks = {
        std::make_unique<TaskControlBlock<millis, std::function<void()>>>(
          std::function<void()>(
            writeRamp), // TODO: why do we need to explicitly cast lambdas to
                        // not crash?
          []() -> millis { return millis(HAL_GetTick()); },
          millis(1),
          millis(0)),
        std::make_unique<TaskControlBlock<millis, LedBreatheAnimation>>(
          led1Breathe,
          []() -> millis { return millis(HAL_GetTick()); },
          millis(20),
          millis(0)),
        std::make_unique<TaskControlBlock<millis, LedToggleAnimation>>(
          led2Toggle,
          []() -> millis { return millis(HAL_GetTick()); },
          millis(800),
          millis(0)),
        std::make_unique<TaskControlBlock<millis, LedToggleAnimation>>(
          led3Toggle,
          []() -> millis { return millis(HAL_GetTick()); },
          millis(600),
          millis(0)),
        std::make_unique<TaskControlBlock<millis, std::function<void()>>>(
          std::function<void()>(task_print_logs),
          []() -> millis { return millis(HAL_GetTick()); },
          millis(100),
          millis(0)),
        std::make_unique<TaskControlBlock<millis, std::function<void()>>>(
          [&led1Breathe, &buttonTime]() {
              // Lambda sets period based on button interrupt
              if (buttonTime.getDiff() > MIN_CYCLE_TIME &&
                  buttonTime.getDiff() < MAX_CYCLE_TIME) {
                  led1Breathe.setPeriod(
                    std::chrono::duration<uint32_t, std::milli>(
                      buttonTime.getDiff()));
              }
          },
          []() -> millis { return millis(HAL_GetTick()); },
          millis(5),
          millis(1))
    };

    // Run tasks, do not return
    scheduler(tasks);
}
